### ISSUE TITLE
[html format] Convert newline characters in cells into line breaks

### ISSUE THREAD

**Issue by sriyerg** [astanin/python-tabulate#126]
If a cell has a newline character (`\n`), it gets ignored when the table is rendered in HTML. I am hoping it is an easy fix to convert it into line breaks (`<br>`). 

Testcase:
```python
import tabulate

table = [["item\nname", "qty"], ["eggs", 451], ["more\nspam", 42]]
print(tabulate.tabulate(table, "firstrow", "html"))
```

Output:
```html
<table>
<thead>
<tr><th>item
name     </th><th style="text-align: right;">  qty</th></tr>
</thead>
<tbody>
<tr><td>eggs</td><td style="text-align: right;">  451</td></tr>
<tr><td>more
spam     </td><td style="text-align: right;">   42</td></tr>
</tbody>
</table>
```

Expected output:
```html
<table>
<thead>
<tr><th>item<br>name     </th><th style="text-align: right;">  qty</th></tr>
</thead>
<tbody>
<tr><td>eggs</td><td style="text-align: right;">  451</td></tr>
<tr><td>more<br>spam     </td><td style="text-align: right;">   42</td></tr>
</tbody>
</table>
```

**Comment by jpsnyder** [comment]
I ran into this issue too. It is because it is only using `html.escape()` to sanitize the values, which doesn't do anything with line breaks.

A hacky workaround you can do is monkeypatch tabulate's `htmlescape` function to replace newlines with `<br>` after escaping.

```python
import tabulate
htmlescape = tabulate.htmlescape
tabulate.htmlescape = lambda text: htmlescape(text).replace("\n", "<br>")
```

This of course is only a partial solution because if won't properly handle indents on the next line if you have them.


Perhaps tabulate should just wrap cell values with strings with `<pre>` ? At least as an option.

**Comment by astanin** [comment]
It can be be easily resolved by pre-processing your data.

I'd argue that keeping "\n" intact is important. In HTML it is just white space, and line breaks are important to keep HTML readable and easily editable.
