### ISSUE TITLE
alignment error with multiline and unicode

### ISSUE THREAD

**Issue by lntuition** [astanin/python-tabulate#28]
hello :) I found some bug while using alignment and multiline with unicode(Korean)
below is simple bug code.

Tests (test.py)
``` python
import tabulate
print(tabulate.WIDE_CHARS_MODE)
 
header = ['Something\nLength', 'Is\nDifferent']
data = [['유니코드\nKorean', 'Is\nDifferent']] # this is Korean
print(tabulate.tabulate(data, header, tablefmt='fancy_grid', stralign='center'))
```

Result
![Screenshot from 2019-12-17 16-48-45](https://user-images.githubusercontent.com/34061042/70975428-44184280-20ed-11ea-94b9-0b872c280d85.png)

Is there some problem with using multiline and alignment with unicode together?
Or there is something wrong with my environment?

**Comment by lntuition** [comment]
I found without alignment is also problem...
Here is example for without alignment(default is maybe left)

![Screenshot from 2019-12-17 17-38-52](https://user-images.githubusercontent.com/34061042/70978965-1da9d580-20f4-11ea-9336-7dc4adf8e164.png)

**Comment by raxod502** [comment]
I would assume this is because tabulate is assuming that an _n_-character string takes _n_ columns to render, which isn't the case with all of Unicode. Here is an example of how combining diacritic handling messed up one of my tables:

![image](https://user-images.githubusercontent.com/6559064/71193875-1f84ad80-2248-11ea-946c-fc6eaeafdd37.png)

In one of my other projects (using Go), I solved the problem by converting table cell contents from a string to a rune array before checking their length (see [here](https://github.com/replit/upm/blob/87e772cbee80af18522a32ce9b464114cb698750/internal/table/table.go#L207)).

**Comment by jquast** [comment]
This looks to be a problem only because of `\n`.
Without `\n` the alignment is correct.

`wcwidth.wcwidth('\n')` returns -1 to indicate the "width" of that character (`\n`) cannot be determined. I've studied the `tabulate` function a bit, and though I am not entirely certain, it doesn't look like the possibility of -1 return value from `wcwidth.wcwidth` is considered?

I can suggest any call to `width_fn` to be wrapped by `max(0, width_fn(...` but I'm not so sure, that doesn't explain why it would be *four* cells off! I can make this attempt at a fix and see if it helps, I think I am wrong though, that would only account for *one* cell of misalignment, not *four*!
