### ISSUE TITLE
Fix all DeprecationWarning from within tabulate

### ISSUE THREAD

**Issue by ssbarnea** [astanin/python-tabulate#3]
@astanin I salute the move from bitbucket to git and github as it makes the project clearly more accesible (and easier to contribute back).

I have a strong interest in keeping tabulate maintained because I use it in https://github.com/ansible/molecule/ and currently I am facing deprecation warning from inside tabulate. Unless tabulate regains its maintenance status, I will be forced to either looks for a replacement or to even fork it.  Example `tabulate.py:1258: DeprecationWarning: invalid escape sequence \e` -- which probably was fixed in master but without are pypi release that is of no help.

If you need help with maintenance, especially CI, packaging, release, let me know. BTW, it would be a good idea to move the repository under an organization so it would not be dependent only on you. For example I am using https://github.com/pycontribs/ for lots of projects and ensure that projects do not have a single human point of failure ;)

**Comment by astanin** [comment]
@ssbarnea Thanks for offering help. I intend to take care of the project, but do not plan to add major features, and cannot dedicate much time to it at the moment. Pull requests that fix compatibility issues are welcome.

Yes, I could use some help in setting up CI, fixing packaging etc. In particular, the new github repo has yet to be setup properly.

I have just uploaded the latest version to PyPI. It took me a while to figure out how to build sdist so it passes twine checks (PyPI docs and error messages were not very helpful). Now the issue is solved and the future updates should come online quicker.

0.8.4 should fix the old Deprecated warning regarding importing ABCs from collections (bitbucket issue 157). The other issue reported by you (bitbucket issue 174) still has to be fixed. Feel free to provide a fix.

https://bitbucket.org/astanin/python-tabulate/issues/157/deprecationwarning-when-running-under-37
https://bitbucket.org/astanin/python-tabulate/issues/174/invalid-escape-sequence

**Comment by ssbarnea** [comment]
Please look at PR above and feel free to cherry pick it, is so big because the was not not previously linted (and the linter would have spotted these issues).
