### ISSUE TITLE
Feature Request: CSV

### ISSUE THREAD

**Issue by lukasc-ch** [astanin/python-tabulate#55]
tabulate already supports a wide variety of output formats. Currently, the very basic CSV format is not one of them. I think it would be a great addition, as it is a standard format to copy-paste data into tools like matlab, excel, ...
Let me know if this feature is desired, then I will add it and open a pull request.

**Comment by cod3licious** [comment]
Yes please! This would be super helpful also for other libraries that use tabulate for logging to more easily switch between useful print and file output!

**Comment by astanin** [comment]
CSV is a data exchange format, white space matters.

Output of tabulate is supposed to be representation format, whitespace can be added liberally.

So if you need to produce CSV, you don't want to align it nicely, because it means padding strings with spaces.
That's why tabulate is not very useful for CSV generation.

Another reason not to use tabulate for CSV generation is performance. Built-in Python module csv is much faster.

Still, if you insist on having commas as separators, consider using `simple_separated_format`:

```
>>> from tabulate import tabulate, simple_separated_format
>>> tabulate([["foo", 1.23],["long bar", 45.6]], tablefmt=simple_separated_format(","))
'foo     , 1.23\nlong bar,45.6'
>>> print(_)
foo     , 1.23
long bar,45.6
```

This formatter won't do everything a CSV writer is supposed to do (like proper escaping),
but it might be enough in some situations.
