### ISSUE TITLE
How to identify how many lines to be printed

### ISSUE THREAD

**Issue by NeilWangziyu** [astanin/python-tabulate#88]
As the title says, for example, I have a dataframe with hundreds of lines, I want to use tabulate to print parts of it. Is it any variables to control the number?

**Comment by astanin** [comment]
Tabulate is not supposed to be used to display the entire dataset, because it has to process the entire data in memory to decide how it should be formatted. For big data sets it can be unnecessary slow.

The recommended way is to extract a slice of the data set you want to print, then pass it to tabulate.
